package com.pgmacdesign.mcwaterslides.client;

import com.pgmacdesign.mcwaterslides.MCWaterSlides;
import com.pgmacdesign.mcwaterslides.machine.PumpHouseMenu;
import net.minecraft.network.chat.Component;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.player.Inventory;

import java.util.List;

/**
 * Vanilla-styled console (texture generated by tools/gen_gui_assets.py): fuel slot with a
 * furnace-style burn flame above it, a cyan RF gauge with a hover tooltip, and a live rate
 * readout under the title.
 */
public class PumpHouseScreen extends AbstractContainerScreen<PumpHouseMenu> {
    private static final ResourceLocation TEXTURE =
            ResourceLocation.fromNamespaceAndPath(MCWaterSlides.MOD_ID, "textures/gui/pump_house.png");

    private static final int GAUGE_X = 152;
    private static final int GAUGE_Y = 20;
    private static final int GAUGE_W = 14;
    private static final int GAUGE_H = 58;

    public PumpHouseScreen(PumpHouseMenu menu, Inventory playerInventory, Component title) {
        super(menu, playerInventory, title);
        this.imageWidth = 176;
        this.imageHeight = 166;
    }

    @Override
    public void render(GuiGraphics graphics, int mouseX, int mouseY, float partialTick) {
        renderBackground(graphics, mouseX, mouseY, partialTick);
        super.render(graphics, mouseX, mouseY, partialTick);
        if (isHovering(GAUGE_X, GAUGE_Y, GAUGE_W, GAUGE_H, mouseX, mouseY)) {
            graphics.renderComponentTooltip(font, List.of(
                    Component.literal(String.format("%,d / %,d RF", menu.energy(), menu.maxEnergy())),
                    Component.literal(menu.genRate() > 0 ? "+" + menu.genRate() + " RF/t" : "idle")
            ), mouseX, mouseY);
        }
        renderTooltip(graphics, mouseX, mouseY);
    }

    @Override
    protected void renderBg(GuiGraphics graphics, float partialTick, int mouseX, int mouseY) {
        graphics.blit(TEXTURE, leftPos, topPos, 0, 0, imageWidth, imageHeight);

        // burn flame above the fuel slot, shrinking bottom-up like the furnace
        if (menu.burnTotal() > 0 && menu.burnRemaining() > 0) {
            int h = Math.max(1, Math.round(14f * menu.burnRemaining() / menu.burnTotal()));
            graphics.blit(TEXTURE, leftPos + 81, topPos + 36 + (14 - h), 176, 14 - h, 14, h);
        }

        // RF gauge fill, bottom-up
        int fill = Math.round(GAUGE_H * (float) menu.energy() / menu.maxEnergy());
        if (fill > 0) {
            graphics.blit(TEXTURE, leftPos + GAUGE_X, topPos + GAUGE_Y + (GAUGE_H - fill),
                    192, GAUGE_H - fill, GAUGE_W, fill);
        }
    }

    @Override
    protected void renderLabels(GuiGraphics graphics, int mouseX, int mouseY) {
        super.renderLabels(graphics, mouseX, mouseY);
        int rate = menu.genRate();
        String text = rate <= 0 ? "idle"
                : rate + " RF/t" + (menu.burnRemaining() > 0 ? "" : " (water)");
        int color = rate <= 0 ? 0x707070 : (menu.burnRemaining() > 0 ? 0x9A5038 : 0x2F6F8F);
        graphics.drawString(font, text, 8, 22, color, false);
    }
}
